apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: twitterclone
  namespace: flux-system
resources:
  - ./apps/twitterclone
images:
  - name: jeanmichelbb/twc-be
    newTag: latest  
  - name: jeanmichelbb/twc-fe
    newTag: latest  