apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: twitterclone
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: twitterclone
  update:
    strategy: Setters
  git:
    commit:
      author:
        name: "FluxCD"
        email: "flux@example.com"