apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: twitterclone-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: twitterclone-backend
  policy:
    semver:
      range: "1.x"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: twitterclone-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: twitterclone-frontend
  policy:
    semver:
      range: "1.x"