apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: twitterclone
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: twitterclone
  filterTags:
    pattern: '^v(?P<version>[0-9]+.[0-9]+.[0-9]+)$'
  policy:
    semver:
      range: ">1.0.0"